# Таблицы структурных преобразований:
# kaz_tags
# eng_tags
# Записи в них соответствуют друг другу

kaz_tags_4_eng_kaz = [
    # kaz nouns

    "<n><nom>$",
    "<n><gen>$",
    "<n><dat>$",
    "<n><acc>$",
    "<n><loc>$",
    "<n><abl>$",
    "<n><ins>$",
    "<n><pl><nom>$",
    "<n><pl><gen>$",
    "<n><pl><dat>$",
    "<n><pl><acc>$",
    "<n><pl><loc>$",
    "<n><pl><abl>$",
    "<n><pl><ins>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><nom>$",
    "<prn><pers><p2><sg><gen>$ <n><px2sg><nom>$",
    "<prn><pers><p2><sg><frm><gen>$ <n><px2sg><frm><nom>$",
    "<prn><pers><p3><sg><gen>$ <n><px3sp><nom>$",
    "<prn><pers><p1><pl><gen>$ <n><px1pl><nom>$",
    "<prn><pers><p2><pl><gen>$ <n><pl><px2sg><nom>$",
    "<prn><pers><p2><pl><frm><gen>$ <n><pl><px2sg><frm><nom>+е<cop><aor><p3><pl>$",
    "<prn><dem><pl><gen>$ <n><pl><px3sp><nom>$",
    "<prn><pers><p1><sg><nom>$ <n><nom>+е<cop><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <n><nom>+е<cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <n><nom>+е<cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <n><nom>+е<cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <n><nom>+е<cop><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <n><nom>+е<cop><aor><p2><pl><err_orth>$",
    "<prn><pers><p2><pl><frm><nom>$ <n><nom>+е<cop><aor><p2><frm><pl><err_orth>$",
    "<prn><pers><p3><pl><nom>$ <n><nom>+е<cop><aor><p3><sg>$",
    "<prn><pers><p1><sg><gen>$ <n><pl><px1sg><nom>$",
    "<prn><pers><p2><sg><gen>$<n><pl><px2sg><nom>$",
    "<prn><pers><p2><sg><frm><gen>$ <n><pl><px2sg><frm><nom>$",
    "<prn><pers><p3><sg><gen>$ <n><pl><px3sp><nom>$",
    "<prn><pers><p1><pl><gen>$ <n><pl><px1pl><nom>$",
    "<prn><pers><p2><pl><gen>$ <n><pl><px2sg><nom>$",
    "<prn><pers><p2><pl><frm><gen>$ <n><pl><px2sg><frm><nom>+е<cop><aor><p3><pl>$",
    "<prn><dem><pl><gen>$ <n><pl><px3sp><nom>$",
    "<prn><pers><p1><sg><nom>$ <n><pl><px1sg><ins>$",
    "<prn><pers><p2><sg><nom>$ <n><pl><px2sg><ins>$",
    "<prn><pers><p2><sg><frm><nom>$ <n><pl><px2sg><frm><ins>$",
    "<prn><pers><p3><sg><nom>$ <n><pl><px3sp><ins>$",
    "<prn><pers><p1><pl><nom>$ <n><pl><px1pl><ins>$",
    "<prn><pers><p2><pl><nom>$ <n><pl><px2sg><ins>$",
    "<prn><pers><p2><pl><frm><nom>$ <n><pl><px2sg><frm><ins>$",
    "<prn><pers><p3><pl><nom>$ <n><pl><px3sp><ins>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><nom>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><gen>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><dat>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><acc>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><loc>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><abl>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><ins>$",

    # kaz nums

    "<num>$",
    "<num><gen>$",
    "<num><dat>$",
    "<num><acc>$",
    "<num><loc>$",
    "<num><abl>$",
    "<num><ins>$",
    "<prn><pers><p1><sg><nom>$<num><subst><nom>+е<cop><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$<num><subst><nom>+е<cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$<num><subst><nom>+е<cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$<num><subst><nom>+е<cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$<num><subst><nom>+е<cop><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$<num><subst><nom>+е<cop><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$<num><subst><nom>+е<cop><aor><p2><frm><pl>$",
    "<prn><pers><p3><pl><nom>$<num><subst><pl><nom>+е<cop><aor><p3><pl>$",
    "<num><ord>$",
    "<num><ord><gen>$",
    "<num><ord><dat>$",
    "<num><ord><acc>$",
    "<num><ord><loc>$",
    "<num><ord><abl>$",
    "<num><ord><ins>$",
    "<num><ord><subst><pl><nom>$",
    "<num><ord><subst><pl><px3sp><gen>$",
    "<num><ord><subst><pl><dat>$",
    "<num><ord><subst><pl><acc>$",
    "<num><ord><subst><pl><loc>$",
    "<num><ord><subst><pl><abl>$",
    "<num><ord><subst><pl><ins>$",
    "<prn><pers><p1><sg><nom>$ <num><ord><subst><nom>+е<cop><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$<num><ord><subst><nom>+е<cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$<num><ord><subst><nom>+е<cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$<num><ord><subst><nom>+е<cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$<num><ord><subst><px1pl><nom>+е<cop><aor><p3><pl>$",
    "<prn><pers><p2><pl><nom>$<num><ord><subst><nom>+е<cop><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$<num><ord><subst><nom>+е<cop><aor><p2><frm><pl>$",
    "<prn><pers><p3><pl><nom>$<num><ord><subst><pl><nom>+е<cop><aor><p3><pl>$",
    "<num><coll><subst><nom>$",
    "<num><coll><subst><gen>$",
    "<num><coll><subst><dat>$",
    "<num><coll><subst><acc>$",
    "<num><coll><subst><loc>$",
    "<num><coll><subst><abl>$",
    "<num><coll><subst><ins>$",
    "<num><subst><sim>$",
    "<num><subst><pl><loc>+е<cop><aor><p3><sg>$",
    "<num><subst><dat>$<adv>$",
    "<num><subst><dat>$<adj><advl>$",
    "<num><subst><abl>$ <num><subst><nom>$ ^е<cop><aor><p3><sg>$",
    "<num><subst><gen>$ <num><subst><nom>$ ^е<cop><aor><p3><sg>$",

    # kaz prn

    "<prn><pers><p1><sg><nom>$",
    "<prn><pers><p1><sg><gen>$",
    "<prn><pers><p1><sg><dat>$",
    "<prn><pers><p1><sg><acc>$",
    "<prn><pers><p1><sg><loc>$",
    "<prn><pers><p1><sg><abl>$",
    "<prn><pers><p1><sg><ins>$",
    "<prn><ref><px1sg><nom>+е<cop><aor><p3><sg>$",
    "<prn><ref><px2sg><nom>+е<cop><aor><p3><sg>$",
    "<prn><ref><px2sg><frm><nom>+е<cop><aor><p3><sg>$",
    "<prn><ref><px3sp><nom>+е<cop><aor><p3><sg>$",
    "<prn><ref><px1pl><nom>+е<cop><aor><p3><pl>$",
    "<prn><ref><px2pl><nom>+е<cop><aor><p3><pl>$",
    "<prn><ref><px2pl><frm><nom>+е<cop><aor><p3><pl>$",
    "<prn><ref><px3pl><nom>+е<cop><aor><p3><pl>$",

    # kaz participle

    "<v><iv><ger_past><pl><nom>$",
    "<v><iv><ger_past><px1sg><nom>$",
    "<v><iv><ger_past><px2sg><nom>$",
    "<v><iv><ger_past><px3sp><nom>$",
    "<v><iv><ger_past><px1pl><nom>$",
    "<v><iv><ger_past><px2sg><frm><nom>$",
    "<v><iv><ger_past><px3sp><nom>$",
    "<v><iv><past><p1><sg>$",
    "<v><iv><past><p2><sg>$",
    "<v><iv><gpr_past>$",
    "<v><iv><past><p1><pl>$",
    "<v><iv><past><p2><frm><sg>$",
    "<v><iv><gpr_past>$",
    "<v><iv><ger_past><dat>$",
    "<v><iv><ger_past><gen>$",

    # kaz verb

    "<prn><pers><p1><sg><nom>$ <v><tv><prc_perf>$ <vaux><pres><p1><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><prc_perf>$ <vaux><pres><p2><frm><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><prc_perf>$ <vaux><opt><p3><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><prc_perf>$ <vaux><pres><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><gna_perf><vaux><pres><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><prc_perf>$ <vaux><pres><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><prc_perf>$ <vaux><pres><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><prc_perf>$ <vaux><pres><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><prc_perf>$<vaux><pres><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><prc_perf>$ <vaux><pres><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><prc_perf>$ <vaux><pres><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><prc_perf>$ <vaux><pres><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><iv><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><aor><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><iv><aor><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><ifi><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><ifi><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><ifi><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><iv><ifi><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><ifi><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><ifi><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><ifi><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><iv><ifi><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><past><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><past><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><past><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><iv><past><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><past><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><past><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><past><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><iv><past><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><pih><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><pih><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><pih><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><iv><pih><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><pih><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><pih><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><pih><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><iv><pih><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><fut><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><fut><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><fut><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><iv><fut><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><fut><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><fut><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><fut><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><iv><fut><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><fut_plan><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><fut_plan><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><fut_plan><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><iv><fut_plan><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><fut_plan><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><fut_plan><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><fut_plan><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><iv><fut_plan><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <v><tv><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <v><tv><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <v><iv><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <v><tv><aor><p2><frm><pl>$",
    "<prn><dem><pl><nom>$ <v><iv><aor><p3><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p1><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p2><frm><sg>$",
    "<prn><pers><p2><sg><nom>$ <v><tv><prc_perf>$ <vaux><opt><p3><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p1><pl>$",
    "<v><tv><gna_perf><vaux><pres><p2><pl>$",
    "<v><tv><prc_perf>$ <vaux><pres><p2><frm><pl>$",
    "<v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p1><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p2><sg>$",
    "<v><tv><prc_perf>$<vaux><pres><p2><frm><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <v><tv><prc_perf>$ <vaux><pres><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <v><tv><prc_perf>$ <vaux><pres><p2><pl>$",
    "<v><tv><prc_perf>$ <vaux><pres><p2><frm><pl>$",
    "<v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<v><tv><aor><p1><sg>$",
    "<v><tv><aor><p2><sg>$",
    "<v><tv><aor><p2><frm><sg>$",
    "<v><iv><aor><p3><sg>$",
    "<v><tv><aor><p1><pl>$",
    "<v><tv><aor><p2><pl>$",
    "<v><tv><aor><p2><frm><pl>$",
    "<v><iv><aor><p3><sg>$",
    "<v><tv><ifi><p1><sg>$",
    "<v><tv><ifi><p2><sg>$",
    "<v><tv><ifi><p2><frm><sg>$",
    "<v><iv><ifi><p3><sg>$",
    "<v><tv><ifi><p1><pl>$",
    "<v><tv><ifi><p2><pl>$",
    "<v><tv><ifi><p2><frm><pl>$",
    "<v><iv><ifi><p3><sg>$",
    "<v><tv><past><p1><sg>$",
    "<v><tv><past><p2><sg>$",
    "<v><tv><past><p2><frm><sg>$",
    "<v><iv><past><p3><sg>$",
    "<v><tv><past><p1><pl>$",
    "<v><tv><past><p2><pl>$",
    "v><tv><past><p2><frm><pl>$",
    "<v><iv><past><p3><sg>$",
    "<v><tv><pih><p1><sg>$",
    "<v><tv><pih><p2><sg>$",
    "<v><tv><pih><p2><frm><sg>$",
    "<v><iv><pih><p3><sg>$",
    "<v><tv><pih><p1><pl>$",
    "<v><tv><pih><p2><pl>$",
    "<v><tv><pih><p2><frm><pl>$",
    "<v><iv><pih><p3><sg>$",
    "<v><tv><fut><p1><sg>$",
    "<v><tv><fut><p2><sg>$",
    "<v><tv><fut><p2><frm><sg>$",
    "<v><iv><fut><p3><sg>$",
    "<v><tv><fut><p1><pl>$",
    "<v><tv><fut><p2><pl>$",
    "<v><tv><fut><p2><frm><pl>$",
    "<v><iv><fut><p3><sg>$",
    "<v><tv><fut_plan><p1><sg>$",
    "<v><tv><fut_plan><p2><sg>$",
    "<v><tv><fut_plan><p2><frm><sg>$",
    "<v><iv><fut_plan><p3><sg>$",
    "<v><tv><fut_plan><p1><pl>$",
    "<v><tv><fut_plan><p2><pl>$",
    "<v><tv><fut_plan><p2><frm><pl>$",
    "<v><iv><fut_plan><p3><sg>$",
    "<v><tv><aor><p1><sg>$",
    "<v><tv><aor><p2><sg>$",
    "<v><tv><aor><p2><frm><sg>$",
    "<v><iv><aor><p3><sg>$",
    "<v><tv><aor><p1><pl>$",
    "<v><tv><aor><p2><pl>$",
    "<v><tv><aor><p2><frm><pl>$",
    "<v><iv><aor><p3><sg>$",

    # kaz adj

    "<adj>$",
    "<adj><subst><gen>$",
    "<adj><subst><dat>$",
    "<adj><subst><acc>$",
    "<adj><subst><abl>$",
    "<adj><subst><ins>$",
    "<adj><comp>$",
    "<adj><comp><subst><gen>$",
    "<adj><comp><subst><dat>$",
    "<adj><comp><subst><acc>$",
    "<adj><comp><subst><ins>$",
    "<adj><comp><subst><abl>$",
    "<adj><comp>$",
    "<adj><comp><subst><gen>$",
    "<adj><comp><subst><dat>$",
    "<adj><comp><subst><acc>$",
    "<adj><comp><subst><abl>$",
    "<adj><comp><subst><ins>$",
    "<adj><comp>$",
    "<adj><comp><gen>$",
    "<adj><comp><dat>$",
    "<adj><comp><acc>$",
    "<adj><comp><abl>$",
    "<adj><comp><ins>$",
    "<adj>$ <cop><aor><p1><sg>$",
    "<adj>$ <cop><aor><p2><sg>$",
    "<adj>$ <cop><aor><p2><frm><sg>$",
    "<adj>$ <cop><aor><p3><sg>$",
    "<adj>$ <cop><aor><p1><pl>$",
    "<adj>$ <cop><aor><p2><pl>$",
    "<adj><subst><pl><nom>$",
    "<prn><pers><p1><sg><nom>$ <adj>$ <cop><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <adj>$ <cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <adj>$ <cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <adj>$ <cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <adj>$ <cop><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <adj>$ <cop><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <adj>$ <cop><aor><p2><frm><pl>$",
    "<prn><pers><p3><pl><nom>$ <adj>$ <cop><aor><p3><sg>$",
    "<adj><subst><pl><nom>$",
    "<adj><subst><pl><gen>$",
    "<adj><subst><pl><dat>$",
    "<adj><subst><pl><acc>$",
    "<adj><subst><pl><abl>$ <cop><aor><p3><sg>$",
    "<adj><subst><pl><ins>$",
    "<adv>$ <adj><subst><nom>$",
    "<adv>$ <adj><subst><gen>$",
    "<adv>$ <adj><subst><dat>$",
    "<adv>$ <adj><subst><acc>$",
    "<adv>$ <adj><subst><abl>$",
    "<adv>$ <adj><subst><ins>$",
    "<prn><pers><p1><sg><nom>$ <adj><comp>$ <cop><aor><p1><sg>$$",
    "<prn><pers><p2><sg><nom>$ <adj><comp>$ <cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <adj><comp>$ <cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <adj><comp>$ ^е<cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <adj><comp>$ <cop><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <adj><comp>$ <cop><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <adj><comp>$ <cop><aor><p2><frm><pl>$",
    "<prn><pers><p3><pl><nom>$ <adj><comp>$ ^е<cop><aor><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <adj><comp>$ <cop><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <adj><comp>$ <cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <adj><comp>$ <cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <adj><comp>$ ^е<cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <adj><comp>$ <cop><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <adj><comp>$ <cop><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <adj><comp>$ <cop><aor><p2><frm><pl>$",
    "<prn><pers><p3><pl><nom>$ <adj><comp>$ ^е<cop><aor><p3><sg>$",
    "<prn><pers><p1><sg><nom>$ <adv>$ <adj>$ <cop><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <adv>$ <adj>$ <cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <adv>$ <adj>$ <cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <adv>$ <adj>$ <cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <adv>$ <adj>$ ^е<cop><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <adv>$ <adj>$ ^е<cop><aor><p2><pl>$",
    "<prn><pers><p2><pl><frm><nom>$ <adv>$ <adj>$ <cop><aor><p2><frm><pl>$",
    "<prn><pers><p1><pl><nom>$ <adv>$ <adj>$ <cop><aor><p1><pl>$",
    "<prn><pers><p3><pl><nom>$ <adv>$ <adj><subst><pl><nom>$ <cop><aor><p3><sg>$",

    # kaz adv

    "<adv>$",
    "<adv><dat>$",
    "<adv><abl>$",
    "<adv><dat>$ <adv>$",
    "<adv><abl>$",
    "<adv><attr>$",
    "<adv><abl>$",
    "<adv><abl>$",

    # kaz conjuct

    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjadv>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<post>$",
    "<postadv>$",
    "<cnjsub>$",
    "<qst>$",

    # пробуем

    "<v><tv><pass><aor><p3><sg>$"
]

eng_tags_4_eng_kaz = [
    # eng nouns

    "<det><def><sp>$ <n><sg>$",
    "<n><sg>$",
    "<pr>$ <n><sg>$",
    "<det><def><sp>$ <n><sg>$",
    "<pr>$ <det><def><sp>$ <n><sg>$",
    "<pr>$ <det><def><sp>$ <n><sg>$",
    "<pr>$ <n><sg>$",
    "<n><pl>$",
    "<pr>$ <n><pl>$",
    "<pr>$ <n><pl>$",
    "<n><pl>$",
    "<pr>$ <n><pl>$",
    "<pr>$ <n><pl>$",
    "<pr>$ <n><pl>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<prn><subj><p1><mf><sg>$<vbser><pres><p1><sg>$ <det><ind><sg>$ <n><sg>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <det><ind><sg>$ <n><sg>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <det><ind><sg>$ <n><sg>$",
    "<prn><subj><p3><nt><sg>$ <vbser><pres><p3><sg>$ <det><ind><sg>$ <n><sg>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <det><ind><sg>$ <n><sg>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <det><ind><sg>$ <n><sg>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <det><ind><sg>$ <n><sg>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <det><ind><sg>$ <n><sg>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<det><pos><sp>$ <n><pl>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$ <pr>$ <det><pos><sp>$ <n><pl>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <pr>$ <det><pos><sp>$ <n><pl>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <pr>$ <det><pos><sp>$ <n><pl>$",
    "<prn><subj><p3><m><sg>$ <pr>$ <n><pl>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <pr>$ <det><pos><sp>$ <n><pl>$",
    "<prn><subj><p2><mf><sp>$ <pr>$ <n><pl>$",
    "<prn><subj><p2><mf><sp>$ <pr>$ <n><pl>$",
    "<prn><subj><p3><mf><pl>$ <pr>$ <n><pl>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",
    "<det><pos><sp>$ <n><sg>$",

    # eng nums

    "<num><sg>$",
    "<pr>$<num><sg>$",
    "<pr>$<num><sg>$",
    "<num><sg>$",
    "<pr>$<num><sg>$",
    "<pr>$<num><sg>$",
    "<pr>$<num><sg>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$ <det><def><sp>$ <num><sg>$",
    "<prn><subj><p2><mf><sp>$<vbser><pres>$ <det><def><sp>$ <num><sg>$",
    "<prn><subj><p2><mf><sp>$<vbser><pres>$ <det><def><sp>$ <num><sg>$",
    "<prn><subj><p3><m><sg>$ <vbser><pres><p3><sg>$ <det><def><sp>$ <num><sg>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <det><def><sp>$ <prn><tn><mf><pl>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <det><def><sp>$ <prn><tn><mf><pl>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <det><def><sp>$ <prn><tn><mf><pl>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <det><def><sp>$ <prn><tn><mf><pl>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<pr>$<det><ord><sp>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$<det><ord><sp>$",
    "<prn><subj><p2><mf><sp>$are/be<vbser><pres>$<det><ord><sp>$",
    "<prn><subj><p2><mf><sp>$are/be<vbser><pres>$<det><ord><sp>$",
    "<prn><subj><p3><m><sg>$ <vbser><pres><p3><sg>$ <det><ord><sp>$",
    "<prn><subj><p1><mf><pl>$<vbser><pres>$ <det><ord><sp>$",
    "<prn><subj><p2><mf><sp>$are/be<vbser><pres>$<det><ord><sp>$",
    "<prn><subj><p2><mf><sp>$are/be<vbser><pres>$<det><ord><sp>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <det><ord><sp>$",
    "<num><sg>$",
    "<pr>$ <num><sg>$",
    "<pr>$ <num><sg>$",
    "<num><sg>$",
    "<pr>$ <num><sg>$",
    "<pr>$ <num><sg>$",
    "<pr>$ <num><sg>$",
    "<pr>$<det><ind><sg>$<n><sg>$",
    "<pr>$<num><sp>$",
    "<pr>$<num><sp>$",
    "<pr>$<num><sp>$",
    "<num><sg>$<det><ord><sp>$",
    "<num><sg>$<det><ord><sp>$",

    # eng prn

    "<prn><subj><p1><mf><sg>$",
    "<prn><pos><mf><sp>$",
    "<pr>$ <prn><obj><p1><mf><sg>$",
    "<prn><obj><p1><mf><sg>$",
    "<prn><subj><p1><mf><sg>$<vbhaver><inf>$",
    "<pr>$ <prn><obj><p1><mf><sg>$",
    "<pr>$ <prn><obj><p1><mf><sg>$",
    "<prn><ref><p1><mf><sg>$",
    "<prn><ref><p2><mf><sg>$",
    "<prn><ref><p2><mf><sg>$",
    "<prn><ref><p3><m><sg>$",
    "<prn><ref><p1><mf><pl>$",
    "<prn><ref><p2><mf><pl>$",
    "<prn><ref><p2><mf><pl>$",
    "<prn><ref><p3><mf><pl>$",

    # eng participle

    "<vblex><ger>$",
    "<det><pos><sp>$ <vblex><subs>$",
    "<det><pos><sp>$ <vblex><subs>$",
    "<det><pos><sp>$ <vblex><subs>$",
    "<det><pos><sp>$ <vblex><subs>$",
    "<det><pos><sp>$ <vblex><subs>$",
    "<det><pos><sp>$ <vblex><subs>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vblex><pres>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vblex><pres>$",
    "<pr>$ <vblex><pp>$",
    "<pr>$ <vblex><pp>$",

    # eng verb

    "<prn><subj><p1><mf><sg>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vblex><pres>$",
    "<prn><subj><p3><m><sg>$ <vblex><pres><p3><sg>$",
    "<prn><subj><p1><mf><pl>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vblex><pres>$",
    "<prn><subj><p3><mf><pl>$ <vblex><pres>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <vblex><ger>$",
    "<prn><subj><p3><m><sg>$ <vbser><pres><p3><sg>$ <vblex><ger>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <vblex><ger>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <vblex><ger>$",
    "<prn><subj><p1><mf><sg>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p3><m><sg>$ <vbhaver><pres><p3><sg>$ <vblex><pp>$ <prn><subj><p3><f><sg>$ <vbhaver><pres><p3><sg>$ <vblex><pp>$",
    "<prn><subj><p1><mf><pl>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p3><mf><pl>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p1><mf><sg>$ <vblex><past>$",
    "<prn><subj><p2><mf><sp>$ <vblex><past>$",
    "<prn><subj><p2><mf><sp>$ <vblex><past>$",
    "<prn><subj><p3><m><sg>$ <vblex><past>$",
    "<prn><subj><p1><mf><pl>$ <vblex><past>$",
    "<prn><subj><p2><mf><sp>$ <vblex><past>$",
    "<prn><subj><p2><mf><sp>$ <vblex><past>$",
    "<prn><subj><p3><mf><pl>$ <vblex><past>$",
    "<prn><subj><p1><mf><sg>$ <vbser><past><p1><sg>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><past>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><past>$ <vblex><ger>$",
    "<prn><subj><p3><m><sg>$ <vbser><past><p3><sg>$ <vblex><ger>$",
    "<prn><subj><p1><mf><pl>$ <vbser><past>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><past>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vbser><past>$ <vblex><ger>$",
    "<prn><subj><p3><mf><pl>$ <vbser><past>$ <vblex><ger>$",
    "<prn><subj><p1><mf><sg>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p3><m><sg>$ <vbhaver><past>$ <vblex><pp>$ <prn><subj><p3><f><sg>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p1><mf><pl>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p3><mf><pl>$ <vbhaver><past>$ <vblex><pp>$",
    "<prn><subj><p1><mf><sg>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p3><m><sg>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p1><mf><pl>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p3><mf><pl>$ <vaux><inf>$ <vblex><pres>$",
    "<prn><subj><p1><mf><sg>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p3><m><sg>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p1><mf><pl>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p3><mf><pl>$ <vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<prn><subj><p1><mf><sg>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p3><m><sg>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p1><mf><pl>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p2><mf><sp>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<prn><subj><p3><mf><pl>$ <vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vblex><pres>$",
    "<vblex><pres>$",
    "<vblex><pres>$",
    "<vblex><pres><p3><sg>$",
    "<vblex><pres>$",
    "<vblex><pres>$",
    "<vblex><pres>$",
    "<vblex><pres>$",
    "<vbser><pres><p1><sg>$ <vblex><ger>$",
    "<vbser><pres>$ <vblex><ger>$",
    "<vbser><pres>$ <vblex><ger>$",
    "<vbser><pres><p3><sg>$ <vblex><ger>$",
    "<vbser><pres>$ <vblex><ger>$",
    "<vbser><pres>$ <vblex><ger>$",
    "<vbser><pres>$ <vblex><ger>$",
    "<vbser><pres>$ <vblex><ger>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres><p3><sg>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vbhaver><pres>$ <vblex><pp>$",
    "<vblex><past>$",
    "<vblex><past>$",
    "<vblex><past>$",
    "<vblex><past>$",
    "<vblex><past>$",
    "<vblex><past>$",
    "<vblex><past>$",
    "<vblex><past>$",
    "<vbser><past><p1><sg>$ <vblex><ger>$",
    "<vbser><past>$ <vblex><ger>$",
    "<vbser><past>$ <vblex><ger>$",
    "<vbser><past><p3><sg>$ <vblex><ger>$",
    "<vbser><past>$ <vblex><ger>$",
    "<vbser><past>$ <vblex><ger>$",
    "<vbser><past>$ <vblex><ger>$",
    "<prn><subj><p3><mf><pl>$ <vbser><past>$ <vblex><ger>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vbhaver><past>$ <vblex><pp>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vblex><pres>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbser><inf>$ <vblex><ger>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",
    "<vaux><inf>$ <vbhaver><pres>$ <vblex><pp>$",

    # eng adj

    "<adj>$",
    "<pr>$ <adj>$",
    "<pr>$ <adj>$",
    "<adj>$",
    "<pr>$ <adj>$",
    "<pr>$ <adj>$",
    "<preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<pr>$ <adj><sint><comp>$",
    "<pr>$ <adj><sint><comp>$",
    "<pr>$ <adj><sint><comp>$",
    "<pr>$ <adj><sint><comp>$",
    "<pr>$ <adj><sint><comp>$",
    "<pr>$ <adj><sint><comp>$",
    "<preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<pr>$ <preadv>$ <adj>$",
    "<adj>$",
    "<adj>$",
    "<adj>$",
    "<adj>$",
    "<adj>$",
    "<adj>$",
    "<adj>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$ <preadv>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <preadv>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <preadv>$",
    "<prn><subj><p3><f><sg>$ <vbser><pres><p3><sg>$ <preadv>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <preadv>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <preadv>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <preadv>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <preadv>$",
    "<adj>$",
    "<pr>$ <adj>$",
    "<pr>$ <adj>$",
    "<pr>$ <adj>$",
    "<pr>$ <adj>$",
    "<pr>$ <adj>$",
    "<adv>$ <adj>$",
    "<pr>$ <adv>$ <adj>$",
    "<pr>$ <adv>$ <adj>$",
    "<pr>$ <adv>$ <adj>$",
    "<pr>$ <adv>$ <adj>$",
    "<pr>$ <adv>$ <adj>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$ <adj><sint><comp>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adj><sint><comp>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adj><sint><comp>$",
    "<prn><subj><p3><f><sg>$ <vbser><pres><p3><sg>$ <adj><sint><comp>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <adj><sint><comp>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adj><sint><comp>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adj><sint><comp>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <adj><sint><comp>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$ <preadv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <pr>$ <preadv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <pr>$ <preadv>$ <adj>$",
    "<prn><subj><p3><f><sg>$ <vbser><pres><p3><sg>$ <preadv>$ <adj>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <pr>$ <preadv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <pr>$ <preadv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <pr>$ <preadv>$ <adj>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <preadv>$ <adj>$",
    "<prn><subj><p1><mf><sg>$ <vbser><pres><p1><sg>$ <adv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adv>$ <adj>$",
    "<prn><subj><p3><f><sg>$ <vbser><pres><p3><sg>$ <adv>$ <adj>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <adv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adv>$ <adj>$",
    "<prn><subj><p2><mf><sp>$ <vbser><pres>$ <adv>$ <adj>$",
    "<prn><subj><p1><mf><pl>$ <vbser><pres>$ <adv>$ <adj>$",
    "<prn><subj><p3><mf><pl>$ <vbser><pres>$ <adv>$ <adj>$",

    # eng adv

    "<adv>$",
    "<adv>$",
    "<pr>$ <adv>$",
    "<pr>$ <adv>$",
    "<pr>$ <adv>$",
    "<adv>$",
    "<pr>$ <adv>$",
    "<pr>$ <adv>$",

    # eng conjuct

    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjadv>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "<cnjcoo>$",
    "",
    "",
    "",

    # пробуем

    "<vaux><inf>$ <vbser><inf>$ <vblex><pp>$"
]
