# Таблицы структурных преобразований:
# kaz_tags
# rus_tags
# Записи в них соответствуют друг другу

kaz_tags_4_kaz_rus = [
    # kaz nouns

    "<n><nom>$",
    "<n><gen>$",
    "<n><dat>$",
    "<n><acc>$",
    "<n><loc>$",
    "<n><abl>$",
    "<n><ins>$",
    "<n><pl><nom>$",
    "<n><pl><gen>$",
    "<n><pl><dat>$",
    "<n><pl><acc>$",
    "<n><pl><loc>$",
    "<n><pl><abl>$",
    "<n><pl><ins>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><nom>$",
    "<prn><pers><p2><sg><gen>$ <n><px2sg><nom>$",
    "<prn><pers><p2><sg><frm><gen>$ <n><px2sg><frm><nom>$",
    "<prn><pers><p3><sg><gen>$ <n><px3sp><nom>$",
    "<prn><pers><p1><pl><gen>$ <n><px1pl><nom>$",
    "<prn><pers><p2><pl><gen>$ <n><pl><px2sg><nom>$",
    "<prn><pers><p2><pl><frm><gen>$ <n><pl><px2sg><frm><nom>+е<cop><aor><p3><pl>$",
    "<prn><dem><pl><gen>$ <n><pl><px3sp><nom>$",
    "<prn><pers><p1><sg><nom>$ <n><nom>+е<cop><aor><p1><sg>$",
    "<prn><pers><p2><sg><nom>$ <n><nom>+е<cop><aor><p2><sg>$",
    "<prn><pers><p2><sg><frm><nom>$ <n><nom>+е<cop><aor><p2><frm><sg>$",
    "<prn><pers><p3><sg><nom>$ <n><nom>+е<cop><aor><p3><sg>$",
    "<prn><pers><p1><pl><nom>$ <n><nom>+е<cop><aor><p1><pl>$",
    "<prn><pers><p2><pl><nom>$ <n><nom>+е<cop><aor><p2><pl><err_orth>$",
    "<prn><pers><p2><pl><frm><nom>$ <n><nom>+е<cop><aor><p2><frm><pl><err_orth>$",
    "<prn><pers><p3><pl><nom>$ <n><nom>+е<cop><aor><p3><sg>$",
    "<prn><pers><p1><sg><gen>$ <n><pl><px1sg><nom>$",
    "<prn><pers><p2><sg><gen>$ <n><pl><px2sg><nom>$",
    "<prn><pers><p2><sg><frm><gen>$ <n><pl><px2sg><frm><nom>$",
    "<prn><pers><p3><sg><gen>$ <n><pl><px3sp><nom>$",
    "<prn><pers><p1><pl><gen>$ <n><pl><px1pl><nom>$",
    "<prn><pers><p2><pl><gen>$ <n><pl><px2sg><nom>$",
    "<prn><pers><p2><pl><frm><gen>$ <n><pl><px2sg><frm><nom>+е<cop><aor><p3><pl>$",
    "<prn><dem><pl><gen>$ <n><pl><px3sp><nom>$",
    "<prn><pers><p1><sg><nom>$ <n><pl><px1sg><ins>$",
    "<prn><pers><p2><sg><nom>$ <n><pl><px2sg><ins>$",
    "<prn><pers><p2><sg><frm><nom>$ <n><pl><px2sg><frm><ins>$",
    "<prn><pers><p3><sg><nom>$ <n><pl><px3sp><ins>$",
    "<prn><pers><p1><pl><nom>$ <n><pl><px1pl><ins>$",
    "<prn><pers><p2><pl><nom>$ <n><pl><px2sg><ins>$",
    "<prn><pers><p2><pl><frm><nom>$ <n><pl><px2sg><frm><ins>$",
    "<prn><pers><p3><pl><nom>$ <n><pl><px3sp><ins>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><nom>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><gen>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><dat>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><acc>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><loc>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><abl>$",
    "<prn><pers><p1><sg><gen>$ <n><px1sg><ins>$",
    "<prn><pers><p1><sg><nom>$ <prn><pers><p2><sg><gen>$ <n><px2sg><nom>+е<cop><aor><p1><sg>$",
    "<prn><pers><p1><sg><nom>$ <n><pl><nom>+е<cop><aor><p1><sg>$",
    "<prn><pers><p1><sg><nom>$ <n><loc>+е<cop><aor><p1><sg>$",
    "<n><pl><px1sg><nom>+е<cop><aor><p2><pl>$",
    "<prn><pers><p1><sg><nom>$ <n><pl><loc>+е<cop><aor><p1><sg>$",
    "<prn><pers><p1><sg><nom>$ <n><pl><px1sg><loc>+е<cop><aor><p1><sg>$",

    # kaz pronouns

    "<prn><pers><p1><sg><nom>$",
    "<prn><pers><p2><sg><nom>$",
    "<prn><pers><p2><sg><frm><nom>$",
    "<prn><pers><p3><sg><nom>$",
    "<prn><pers><p3><sg><nom>$",
    "<prn><pers><p3><sg><nom>$",
    "<prn><pers><p1><pl><nom>$",
    "<prn><pers><p2><pl><nom>$",
    "<prn><pers><p2><pl><frm><nom>$",
    "<prn><pers><p3><pl><nom>+е<cop><aor><p3><sg>$",
    "<prn><pers><p1><sg><gen>$",
    "<prn><pers><p1><sg><gen>$",
    "<prn><pers><p1><sg><gen>$",
    "<prn><pers><p1><sg><dat>$",
    "<prn><pers><p1><sg><acc>$",
    "<prn><pers><p1><sg><loc>$",
    "<prn><pers><p1><sg><abl>$",
    "<prn><pers><p1><sg><ins>$",
    "<prn><pers><p2><sg><gen>$",
    "<prn><pers><p2><sg><dat>$",
    "<prn><pers><p2><sg><gen>$",
    "<prn><pers><p2><sg><loc>$",
    "<prn><pers><p2><sg><abl>$",
    "<prn><pers><p2><sg><ins>$",
    "<prn><pers><p2><sg><frm><gen>$",
    "<prn><pers><p2><sg><frm><dat>$",
    "<prn><pers><p2><sg><frm><acc>$",
    "<prn><pers><p2><sg><frm><abl>$",
    "<prn><pers><p2><sg><frm><loc>$",
    "<prn><pers><p1><pl><gen>$",
    "<prn><pers><p1><pl><dat>$",
    "<prn><pers><p1><pl><acc>$",
    "<prn><pers><p1><pl><loc>$",
    "<prn><pers><p1><pl><abl>$",
    "<prn><pers><p1><pl><ins>$",
    "<prn><pers><p2><pl><gen>$",
    "<prn><pers><p2><pl><dat>$",
    "<prn><pers><p2><pl><acc>$",
    "<prn><pers><p2><pl><loc>$",
    "<prn><pers><p2><pl><abl>$",
    "<prn><pers><p2><pl><ins>$",
    "<prn><pers><p2><pl><frm><gen>$",
    "<prn><pers><p2><pl><frm><dat>$",
    "<prn><pers><p2><pl><frm><acc>$",
    "<prn><pers><p2><pl><frm><loc>$",
    "<prn><pers><p2><pl><frm><abl>$",
    "<prn><pers><p2><pl><frm><ins>$",
    "<prn><dem><pl><gen>$",
    "<prn><dem><pl><dat>$",
    "<prn><dem><pl><acc>$",
    "<prn><dem><pl><loc>$",
    "<prn><dem><pl><abl>$",
    "<prn><dem><pl><ins>$",
    "<prn><dem><nom>$",
    "<prn><dem><abl>$",
    "<prn><dem><dat>$",
    "<prn><dem><nom>$",
    "<prn><dem><gen>$",
    "<prn><dem><dat>$",
    "<prn><dem><acc>$",
    "<prn><dem><abl>$",
    "<prn><dem><ins>$",
    "<det><dem>$",
    "<prn><dem><gen>$",
    "<prn><dem><dat>$",
    "<prn><dem><acc>$",
    "<prn><dem><loc>$",
    "<prn><dem><abl>$",
    "<prn><dem><ins>$",
    "<det><dem>$",
    "<prn><dem><nom>$",
    "<det><dem>$",
    "<prn><ref><px1sg><nom>$",
    "<prn><ref><px2sg><nom>$",
    "<prn><ref><px2sg><frm><nom>$",
    "<prn><ref><px3sp><nom>$",
    "<prn><ref><px1pl><nom>$",
    "<prn><ref><px2pl><frm><nom>+е<cop><aor><p3><sg>$",
    "<prn><ind><nom>",
    "<prn><qnt><nom>$",
    "<adj>$",
    "<det><ind>$",
    "<det><qnt>$",
    "<det><qnt>$",
    "<prn><ind><nom>+е<cop><aor><p3><sg>$",
    "<adv>$",
    "<ij>$",
    "<prn><qnt><nom>$",
    "<adv>$",
    "<adv>$",
    "<adv>$",
    "<adj>$",
    "<adj>$",
    "<prn><qnt><px3sp><nom>$",
    "<det><qnt>$",
    "<adj>+е<cop><aor><p3><sg>$",
    "<prn><neg><nom>$",
    "<det><neg>$",
    "<n><nom>$",
    "<adv>$",
    "<det><neg>$",
    "<adv>$",
    "<prn><neg><acc>",
    "<prn><neg><nom>$",
    "<prn><neg><nom>+е<cop><aor><p3><sg>$",

    # kaz есімше

    "^бар<v><iv><ger_past><pl><nom>$",
    "^бар<v><iv><ger_past><px1sg><nom>$",
    "^бар<v><iv><ger_past><px2sg><nom>$",
    "^бар<v><iv><ger_past><px3sp><nom>$",
    "^бар<v><iv><ger_past><px1pl><nom>$",
    "^бар<v><iv><ger_past><px2sg><frm><nom>$",
    "^бар<v><iv><ger_past><px3sp><nom>$",
    "^бар<v><iv><past><p1><sg>$",
    "^бар<v><iv><ger_past><dat>$",
    "^бар<v><iv><ger_past><gen>$",

    # kaz verbs

    "<v><tv><imp>$",
    "<v><tv><ifi><p1><sg>$",
    "<v><tv><ifi><p1><pl>$",
    "<v><tv><ifi><p2><sg>$",
    "<v><tv><ifi><p2><pl>$",
    "<v><tv><ifi><p3><sg>$",
    "<v><tv><ifi><p3><pl>$",
    "<v><tv><past><p1><sg>$",
    "<v><tv><past><p1><pl>$",
    "<v><tv><past><p2><sg>$",
    "<v><tv><past><p2><pl>$",
    "<v><tv><past><p3><sg>$",
    "<v><tv><past><p3><pl>$",
    "<v><tv><ifi><evid><p1><sg>$",
    "<v><tv><ifi><evid><p1><pl>$",
    "<v><tv><ifi><evid><p2><sg>$",
    "<v><tv><ifi><evid><p2><pl>$",
    "<v><tv><ifi><evid><p3><sg>$",
    "<v><tv><ifi><evid><p3><pl>$",
    "<v><tv><pih><p1><sg>$",
    "<v><tv><pih><p1><pl>$",
    "<v><tv><pih><p2><sg>$",
    "<v><tv><pih><p2><pl>$",
    "<v><tv><pih><p3><sg>$",
    "<v><tv><pih><p3><pl>$",
    "<v><tv><prc_perf>$ <vaux><pres><p1><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p1><pl>$",
    "<v><tv><prc_perf>$ <vaux><pres><p2><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p2><pl>$",
    "<v><tv><prc_perf>$ <vaux><pres><p3><sg>$",
    "<v><tv><prc_perf>$ <vaux><pres><p3><pl>$",
    "<v><tv><fut><p1><sg>$",
    "<v><tv><fut><p1><pl>$",
    "<v><tv><fut><p2><sg>$",
    "<v><tv><fut><p2><pl>$",
    "<v><tv><fut><p3><sg>$",
    "<v><tv><fut><p3><pl>$",
    "<v><tv><fut_plan><p1><sg>$",
    "<v><tv><fut_plan><p1><pl>$",
    "<v><tv><fut_plan><p2><sg>$",
    "<v><tv><fut_plan><p2><pl>$",
    "<v><tv><fut_plan><p3><sg>$",
    "<v><tv><fut_plan><p3><pl>$",
    "<v><tv><aor><p1><sg>$",
    "<v><tv><aor><p1><pl>$",
    "<v><tv><aor><p2><sg>$",
    "<v><tv><aor><p2><pl>$",
    "<v><tv><aor><p3><sg>$",
    "<v><tv><aor><p3><pl>$",
    "<v><tv><prc_vol><p1><sg>$ <v><iv><aor><p3><pl>$",
    "<v><tv><prc_vol><p1><pl>$ <v><iv><aor><p3><pl>$",
    "<v><tv><prc_vol><p2><sg>$ <v><iv><aor><p3><pl>$",
    "<v><tv><prc_vol><p2><pl>$ <v><iv><aor><p3><pl>$",
    "<v><tv><prc_vol><p3><sg>$ <v><iv><aor><p3><pl>$",
    "<v><tv><prc_vol><p3><pl>$ <v><iv><aor><p3><pl>$",
    "<v><tv><gna_cond><p1><sg>$",
    "<v><tv><gna_cond><p1><pl>$",
    "<v><tv><gna_cond><p2><sg>$",
    "<v><tv><gna_cond><p2><pl>$",
    "<v><tv><gna_cond><p3><sg>$",
    "<v><tv><gna_cond><p3><pl>$",
    "<v><tv><opt><p1><sg>$",
    "<v><tv><opt><p1><pl>$",
    "<v><tv><opt><p2><sg>$",
    "<v><tv><opt><p2><pl>$",
    "<v><tv><opt><p3><sg>$",
    "<v><tv><opt><p3><pl>$",

    # kaz numerals

    "<num><subst><gen>$",
    "<num><subst><dat>$",
    "<num><subst><loc>$",
    "<num><subst><abl>$",
    "<num><subst><ins>$",
    "<num><subst><px1sg><nom>$",
    "<num><subst><pl><px1sg><nom>$",
    "<num><subst><px2sg><nom>$",
    "<num><subst><pl><px2sg><nom>$",
    "<num><subst><px3sp><nom>$",
    "<num><ord><subst><gen>$",
    "<num><ord><subst><dat>$",
    "<num><ord><subst><loc>$",
    "<num><ord><subst><abl>$",
    "<num><ord><subst><ins>$",
    "<num><ord><subst><nom>+е<cop><aor><p1><sg>$",
    "<num><ord><subst><nom>+е<cop><aor><p1><pl>$",
    "<num><ord><subst><nom>+е<cop><aor><p2><sg>$",
    "<num><ord><subst><nom>+е<cop><aor><p2><pl>$",
    "<num><ord><subst><nom>+е<cop><aor><p3><sg>$",
    "<num><ord><subst><nom>+е<cop><aor><p3><pl>$",
    "<num><ord><subst><px1sg><nom>$",
    "<num><ord><subst><px1pl><nom>$",
    "<num><ord><subst><px2sg><nom>$",
    "<num><ord><subst><pl><px2sg><nom>$",
    "<num><ord><subst><px3sp><nom>$",
    "<num><ord><subst><pl><px3sp><nom>$",
    "<num><coll><subst><nom>+е<cop><aor><p1><sg>$",
    "<num><coll><subst><nom>+е<cop><aor><p1><pl>$",
    "<num><coll><subst><nom>+е<cop><aor><p2><sg>$",
    "<num><coll><subst><nom>+е<cop><aor><p2><pl>$",
    "<num><coll><subst><nom>+е<cop><aor><p3><sg>$",
    "<num><coll><subst><nom>+е<cop><aor><p3><pl>$",
    "<num><coll><subst><gen>$",
    "<num><coll><subst><dat>$",
    "<num><coll><subst><loc>$",
    "<num><coll><subst><abl>$",
    "<num><coll><subst><ins>$",
    "<num><coll><subst><px1sg><nom>$",
    "<num><ord><subst><pl><nom>$",
    "<num><ord><subst><pl><gen>$",
    "<num><ord><subst><pl><dat>$",
    "<num><ord><subst><pl><loc>$",
    "<num><ord><subst><pl><abl>$",
    "<num><ord><subst><pl><ins>$",
    "<num><coll><subst><px1sg><gen>$",
    "<num><coll><subst><px1sg><dat>$",
    "<num><coll><subst><px1sg><loc>$",
    "<num><coll><subst><px1sg><abl>$",
    "<num><coll><subst><px1sg><ins>$",
    "<num><coll><subst><px1pl><gen>$",
    "<num><coll><subst><px1pl><dat>$",
    "<num><coll><subst><px1pl><loc>$",
    "<num><coll><subst><px1pl><abl>$",
    "<num><coll><subst><px1pl><ins>$",
    "<num><coll><subst><px2sg><gen>$",
    "<num><coll><subst><px2sg><dat>$",
    "<num><coll><subst><px2sg><loc>$",
    "<num><coll><subst><px2sg><abl>$",
    "<num><coll><subst><px2sg><ins>$",
    "<num><coll><subst><pl><px2sg><gen>$",
    "<num><coll><subst><pl><px2sg><dat>$",
    "<num><coll><subst><pl><px2sg><loc>$",
    "<num><coll><subst><pl><px2sg><abl>$",
    "<num><coll><subst><pl><px2sg><ins>$",
    "<num><coll><subst><px3sp><gen>$",
    "<num><coll><subst><px3sp><dat>$",
    "<num><coll><subst><px3sp><loc>$",
    "<num><coll><subst><px3sp><abl>$",
    "<num><coll><subst><px3sp><ins>$",
    "<num><coll><subst><pl><px3sp><gen>$",
    "<num><coll><subst><pl><px3sp><dat>$",
    "<num><coll><subst><pl><px3sp><loc>$",
    "<num><coll><subst><pl><px3sp><abl>$",
    "<num><coll><subst><pl><px3sp><ins>$",
    "<num><subst><loc>+е<cop><aor><p1><sg>$",
    "<num><subst><loc>+е<cop><aor><p2><sg>$",
    "<num><subst><loc>+е<cop><aor><p3><sg>$",
    "<num><subst><loc>+е<cop><aor><p1><pl>$",
    "<num><subst><loc>+е<cop><aor><p2><pl>$",
    "<num><subst><loc>+е<cop><aor><p3><pl>$"
]

rus_tags_4_kaz_rus = [
    # rus nouns

    "<n><f><nn><sg><nom>$",
    "<n><f><nn><sg><gen>$",
    "<pr>$ <n><f><nn><sg><dat>$",
    "<n><f><nn><sg><acc>$",
    "<pr>$ <n><f><nn><sg><prp>$",
    "<pr>$ ^<n><f><nn><sg><gen>$",
    "<pr>$ ^<n><f><nn><sg><ins>$",
    "<n><f><nn><pl><nom>$",
    "<n><f><nn><pl><gen>$",
    "<pr>$ <n><f><nn><pl><gen>$",
    "<n><f><nn><pl><gen>$",
    "<pr>$ <n><f><nn><pl><prp>$",
    "<pr>$ <n><f><nn><pl><gen$",
    "<pr>$ <n><f><nn><pl><ins>$",
    "<det><pos><f><an><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pos><f><an><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pos><f><an><sg><nom>$ <n><f><nn><sg><nom>$",
    "<det><pos>$ <n><f><nn><sg><nom>$",
    "<prn><pos><f><an><sg><nom>$ <n><f><nn><sg><nom>$",
    "det><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<det><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<det><pos>$ <n><f><nn><sg><gen>$",
    "<prn><pers><p1><mf><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pers><p2><mf><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pers><p2><mf><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pers><p3><m><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pers><p1><mf><pl><nom>$ <n><f><nn><sg><gen>$",
    "<prn><pers><p2><mf><sg><nom>$ <n><f><nn><sg><gen>$",
    "<prn><pers><p2><mf><sg><nom>$ <n><f><nn><sg><gen>$",
    "<prn><pers><p3><mfn><pl><nom>$ <n><f><nn><sg><gen>$",
    "<prn><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<prn><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<det><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<det><pos>$ <n><f><nn><sg><nom>$",
    "<det><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<det><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<det><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<det><pos>$ <n><f><nn><sg><gen>$",
    "<prn><pers><p1><mf><sg><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pers><p2><mf><sg><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pers><p2><mf><sg><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pers><p3><m><sg><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pers><p1><mf><pl><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pers><p2><mf><sg><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pers><p2><mf><sg><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pers><p3><mfn><pl><nom>$ <pr>$ <n><f><nn><pl><ins>$",
    "<prn><pos><f><an><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pos><f><an><sg><gen>$ <n><f><nn><sg><ins>$",
    "<prn><pos><f><an><sg><gen>$ <n><f><nn><sg><prp>$",
    "<prn><pos><f><an><sg><acc>$ <n><f><nn><sg><acc>$",
    "<pr>$ <prn><pos><f><an><sg><gen>$ <n><f><nn><sg><gen>$",
    "<pr>$ <prn><pos><f><an><sg><gen>$ <n><f><nn><sg><gen>$",
    "<pr>$ <prn><pos><f><an><sg><gen>$ <n><f><nn><sg><ins>$",
    "<prn><pers><p1><mf><sg><nom>$ <prn><pos><f><an><sg><nom>$ <n><f><nn><sg><nom>$",
    "<prn><pers><p1><mf><sg><nom>$ <n><f><nn><sg><gen>$",
    "<prn><pers><p1><mf><sg><nom>$ <pr>$ <n><f><nn><sg><prp>$",
    "<prn><pers><p2><mf><sg><nom>$ <prn><pos><mfn><an><pl><nom>$ <n><f><nn><sg><gen>$",
    "<prn><pers><p1><mf><sg><nom>$ <pr>$ <n><f><nn><pl><dat>$",
    "<prn><pers><p1><mf><pl><nom>$ <pr>$ <prn><pos><mfn><an><pl><dat>$ <n><f><nn><pl><dat>$",

    # rus pronouns

    "<prn><pers><p1><mf><sg><nom>$",
    "<prn><pers><p2><mf><sg><nom>$",
    "<prn><pers><p2><mf><sg><nom>$",
    "<prn><pers><p3><m><sg><nom>$",
    "<prn><pers><p3><nt><sg><nom>$",
    "<prn><pers><p3><f><sg><nom>$",
    "<prn><pers><p1><mf><pl><nom>$",
    "<prn><pers><p2><mf><sg><nom>$",
    "<prn><pers><p2><mf><sg><nom>$",
    "<prn><pers><p3><mfn><pl><nom>$",
    "<prn><pos><m><an><sg><nom>$",
    "<prn><pos><nt><an><sg><nom>$",
    "<prn><pos><f><an><sg><nom>$",
    "<prn><pers><p1><mf><sg><dat>$",
    "<prn><pers><p1><mf><sg><gen>$",
    "<pr>$ <prn><pers><p1><mf><sg><gen>$",
    "<pr>$ <prn><pers><p1><mf><sg><gen>$",
    "<pr>$ <prn><pers><p1><mf><sg><ins>$",
    "<prn><pos><m><an><sg><nom>$",
    "<prn><pers><p2><mf><sg><dat>$",
    "<prn><pos><m><an><sg><nom>$",
    "<pr>$ <prn><pers><p2><mf><sg><gen>$",
    "<pr>$ <prn><pers><p2><mf><sg><gen>$",
    "<pr>$ <prn><pers><p2><mf><sg><ins>$",
    "<prn><pos><m><an><sg><nom>$",
    "<pr>$ <prn><pers><p2><mf><pl><dat>$",
    "<prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><gen>$",
    "<prn><pos><m><an><sg><nom>$",
    "<pr>$ <prn><pers><p1><mf><pl><dat>$",
    "<prn><pers><p1><mf><pl><gen>$",
    "<pr>$ <prn><pers><p1><mf><pl><gen>$",
    "<pr>$ <prn><pers><p1><mf><pl><gen>$",
    "<pr>$ <prn><pers><p1><mf><pl><ins>$",
    "<det><pos><mfn><an><pl><nom>$",
    "<prn><pers><p2><mf><pl><dat>$",
    "<prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><ins>$",
    "<prn><pers><p2><mf><pl><gen>$",
    "<prn><pers><p2><mf><pl><dat>$",
    "<prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><gen>$",
    "<pr>$ <prn><pers><p2><mf><pl><ins>$",
    "<pr>$ <prn><pers><p3><mfn><pl><gen><pprep>$",
    "<prn><pers><p3><nt><sg><ins>$",
    "<prn><pers><p3><mfn><pl><gen>$",
    "<pr>$ <prn><pers><p3><mfn><pl><gen><pprep>$",
    "<pr>$ <prn><pers><p3><mfn><pl><gen><pprep>$",
    "<pr>$ <prn><pers><p3><mfn><pl><ins>$",
    "<prn><dem><nt><sg><nom>$",
    "<pr>$ <prn><dem><nt><sg><gen>$",
    "<pr>$ <prn><dem><nt><sg><dat>$",
    "<prn><dem><nt><sg><nom>$",
    "<prn><dem><nt><sg><gen>$",
    "<pr>$ <prn><dem><nt><sg><dat>$",
    "<prn><dem><nt><sg><nom>$",
    "<pr>$ <prn><dem><nt><sg><gen>$",
    "<pr>$ <prn><dem><nt><sg><ins>$",
    "<prn><dem><m><an><sg><nom>$",
    "<prn><dem><nt><an><sg><gen>$",
    "<prn><dem><nt><an><sg><dat>",
    "<pr>$ <prn><dem><nt><an><sg><gen>$",
    "<pr>$ <prn><dem><nt><an><sg><gen>$",
    "<pr>$ <prn><dem><nt><an><sg><gen>$",
    "<prn><dem><nt><an><sg><ins>",
    "<prn><dem><m><an><sg><nom>$",
    "<det><dem><m><an><sg><nom>$",
    "<prn><dem><m><an><sg><nom>$",
    "<det><ref><f><an><sg><nom>$",
    "<det><ref><m><an><sg><nom>$",
    "<det><ref><mfn><an><pl><nom>$",
    "<det><ref><m><an><sg><nom>$",
    "<det><ref><mfn><an><pl><nom>$",
    "<det><ref><mfn><an><pl><nom>$",
    "<prn><ind><m><aa><sg><nom>$",
    "<prn><ind><mfn><an><pl><nom>$",
    "<prn><ind><mfn><an><pl><nom>$",
    "<prn><ind><mfn><an><pl><nom>$",
    "<det><def><m><an><sg><nom>$",
    "<adv>$",
    "<prn><ind><nt><sg><nom>$",
    "<pr>$<guio>$<n><nt><nn><sg><dat>$",
    "<adv>$",
    "<det><def><m><an><sg><nom>$",
    "<adv>$",
    "<adj><sint><short><nt><sg>$",
    "<adv>$",
    "<prn><def><mfn><an><pl><nom>",
    "<prn><def><mfn><an><pl><nom>",
    "<prn><def><mfn><an><pl><nom>",
    "<prn><def><mfn><an><pl><nom>",
    "<prn><def><mfn><an><pl><nom>",
    "<prn><neg><m><aa><sg><nom>$",
    "<prn><neg><m><aa><sg><nom>$",
    "<prn><neg><nt><nn><sg><gen>$",
    "<adv>$",
    "<prn><ind><m><an><sg><nom>$",
    "<adv>$",
    "<prn><neg><m><aa><sg><gen>$",
    "<prn><neg><nt><nn><sg><gen>$",
    "<prn><neg><nt><nn><sg><gen>$",

    # rus есімше

    "<vblex><impf><iv><pp><actv><mfn><an><pl><nom>$",
    "<prn><pos><nt><an><sg><nom>$ <n><nt><nn><sg><nom>$",
    "<vblex><impf><iv><inf>$",
    "<vblex><impf><iv><pp><actv><m><an><sg><nom>$",
    "<vblex><impf><iv><pp><actv><m><an><sg><nom>$",
    "<vblex><impf><iv><inf>$",
    "<vblex><impf><iv><pp><actv><m><an><sg><nom>$",
    "<prn><pers><p1><mf><sg><nom>$ <vblex><impf><iv><past><m><sg>$",
    "<pr>$ <vblex><impf><iv><pp><actv><m><an><sg><dat>$",
    "<vblex><impf><iv><pp><actv><m><an><sg><gen>$",

    # rus verbs

    "<vblex><perf><tv><inf>$",
    "<vblex><perf><tv><past><f><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><f><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><f><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><f><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><perf><tv><past><m><sg>$",
    "<vblex><perf><tv><past><mfn><pl>$",
    "<vblex><impf><tv><pres><p1><sg>$",
    "<vblex><impf><tv><pres><p1><pl>$",
    "<vblex><impf><tv><pres><p2><sg>$",
    "<vblex><impf><tv><pres><p2><pl>$",
    "<vblex><impf><tv><pres><p3><sg>$",
    "<vblex><impf><tv><pres><p3><pl>$",
    "<vbmod><impf><iv><pres><p3><sg>$ <vblex><perf><tv><fut><p1><sg>$",
    "<vbmod><impf><iv><pres><p3><sg>$ <vblex><perf><tv><fut><p1><pl>$",
    "<vbmod><impf><iv><pres><p3><sg>$ <vblex><perf><tv><fut><p2><sg>$",
    "<vbmod><impf><iv><pres><p3><sg>$ <vblex><perf><tv><fut><p2><pl>$",
    "<vbmod><impf><iv><pres><p3><sg>$ <vblex><perf><tv><fut><p3><sg>$",
    "<vbmod><impf><iv><pres><p3><sg>$ <vblex><perf><tv><fut><p3><pl>$",
    "<vblex><impf><iv><pres><p1><sg>$ <vblex><perf><tv><inf>$",
    "<vblex><impf><iv><pres><p1><pl>$ <vblex><perf><tv><inf>$",
    "<vblex><impf><iv><pres><p2><sg>$ <vblex><perf><tv><inf>$",
    "<vblex><impf><iv><pres><p2><pl>$ <vblex><perf><tv><inf>$",
    "<vblex><impf><iv><pres><p3><sg>$ <vblex><perf><tv><inf>$",
    "<vblex><impf><iv><pres><p3><pl>$ <vblex><perf><tv><inf>$",
    "<vblex><perf><tv><fut><p1><sg>$",
    "<vblex><perf><tv><fut><p1><pl>$",
    "<vblex><perf><tv><fut><p2><sg>$",
    "<vblex><perf><tv><fut><p2><pl>$",
    "<vblex><perf><tv><fut><p3><sg>$",
    "<vblex><perf><tv><fut><p3><pl>$",
    "<vbmod><impf><pres><p1><sg>$ <vblex><perf><tv><inf>$",
    "<vbmod><impf><pres><p1><pl>$ <vblex><perf><tv><inf>$",
    "<vbmod><impf><pres><p2><sg>$ <vblex><perf><tv><inf>$",
    "<vbmod><impf><pres><p2><pl>$ <vblex><perf><tv><inf>$",
    "<vbmod><impf><pres><p3><sg>$ <vblex><perf><tv><inf>$",
    "<vbmod><impf><pres><p3><pl>$ <vblex><perf><tv><inf>$",
    "<cnjsub>$ <vblex><perf><tv><fut><p1><sg>$",
    "<cnjsub>$ <vblex><perf><tv><fut><p1><pl>$",
    "<cnjsub>$ <vblex><perf><tv><fut><p2><sg>$",
    "<cnjsub>$ <vblex><perf><tv><fut><p2><pl>$",
    "<cnjsub>$ <vblex><perf><tv><fut><p3><sg>$",
    "<cnjsub>$ <vblex><perf><tv><fut><p3><pl>$",
    "<vblex><perf><tv><fut><p1><sg>$",
    "<vblex><perf><tv><fut><p1><pl>$",
    "<vblex><perf><tv><fut><p2><sg>$",
    "<vblex><perf><tv><fut><p2><pl>$",
    "<vblex><perf><tv><fut><p3><sg>$",
    "<vblex><perf><tv><fut><p3><pl>$",

    # rus numerals

    "<num><mfn><pl><gen>$",
    "<pr>$ <num><mfn><pl><dat>$",
    "<num><mfn><pl><acc>$",
    "<pr>$ <num><mfn><pl><prp>$",
    "<num><mfn><pl><ins>$",
    "<prn><pos><m><an><sg><nom>$ <num><mfn><pl><nom>$",
    "<prn><pos><m><an><sg><nom>$ <num><mfn><pl><nom>$",
    "<prn><pos><m><an><sg><nom>$ <num><mfn><pl><nom>$",
    "<prn><pos><m><an><sg><nom>$ <num><mfn><pl><nom>$",
    "<prn><pos><m><an><sg><nom>$ <num><mfn><pl><nom>$",
    "<det><ord><nt><an><sg><gen>$",
    "<pr>$ det><ord><nt><an><sg><dat>$",
    "<det><ord><m><nn><sg><acc>$",
    "<pr>$ <det><ord><nt><an><sg><gen>$",
    "<det><ord><nt><an><sg><ins>$",
    "<det><ord><m><an><sg><nom>$",
    "<det><ord><mfn><an><pl><nom>$",
    "<det><ord><m><an><sg><nom>$",
    "<det><ord><mfn><an><pl><nom>$",
    "<det><ord><m><an><sg><nom>$",
    "<det><ord><mfn><an><pl><nom>$",
    "<prn><pos><m><an><sg><nom>$ <det><ord><m><an><sg><nom>$",
    "<prn><pos><m><an><sg><nom>$ <det><ord><m><an><sg><nom>$",
    "<prn><pos><m><an><sg><nom>$ <det><ord><m><an><sg><nom>$",
    "<prn><pos><m><an><sg><nom>$ <det><ord><m><an><sg><nom>$",
    "<prn><pos><m><an><sg><nom>$ <det><ord><m><an><sg><nom>$",
    "<prn><pos><m><an><sg><nom>$ <det><ord><m><an><sg><nom>$",
    "<prn><pers><p1><mf><sg><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<prn><pers><p1><mf><pl><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<prn><pers><p2><mf><sg><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<prn><pers><p2><mf><pl><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<prn><pers><p3><mf><sg><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<prn><pers><p3><mf><pl><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<num><coll><mfn><aa><pl><acc>$",
    "<pr>$ <num><coll><mfn><an><pl><dat>$",
    "<num><coll><mfn><aa><pl><acc>$",
    "<pr>$ <num><coll><mfn><aa><pl><prp>$",
    "<num><coll><mfn><an><pl><ins>$",
    "<num><coll><mfn><an><pl><nom>$",
    "<det><ord><mfn><an><pl><nom>$",
    "<det><ord><mfn><an><pl><gen>$",
    "<pr>$ <det><ord><m><an><sg><ins>$",
    "<det><ord><mfn><an><pl><nom>$",
    "<pr>$ <det><ord><mfn><an><pl><prp>$",
    "<det><ord><mfn><an><pl><ins>$",
    "<det><pos><mfn><aa><pl><acc>$ <num><coll><mfn><aa><pl><acc>$",
    "<prn><pos><nt><an><sg><ins>$ <num><coll><mfn><an><pl><dat>$",
    "<prn><pos><mfn><an><pl><nom>$ <num><coll><mfn><an><pl><nom>$",
    "<pr>$ <prn><pers><p1><mf><sg><gen>$ <num><coll><mfn><an><pl><prp>$",
    "<pr>$ <prn><pers><p1><mf><sg><ins>$ <num><coll><mfn><an><pl><ins>$",
    "<prn><pos><mfn><an><pl><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<prn><pos><nt><an><sg><ins>$ <num><coll><mfn><an><pl><dat>$",
    "<prn><pos><mfn><aa><pl><acc>$ <num><coll><mfn><an><pl><nom>$",
    "<pr>$ <prn><pos><mfn><an><pl><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<pr>$ <prn><pos><mfn><an><pl><ins>$ <num><coll><mfn><an><pl><ins>$",
    "<det><pos><mfn><aa><pl><acc>$ <num><coll><mfn><aa><pl><acc>$",
    "<prn><pos><nt><an><sg><ins>$ <num><coll><mfn><an><pl><dat>$",
    "<prn><pos><mfn><an><pl><nom>$ <num><coll><mfn><an><pl><nom>$",
    "<pr>$ <det><pos><mfn><aa><pl><acc>$ <num><coll><mfn><aa><pl><acc>$",
    "<pr>$ <prn><pos><mfn><an><pl><ins>$ <num><coll><mfn><an><pl><ins>$",
    "<prn><pos><mfn><an><pl><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<prn><pos><nt><an><sg><ins>$ <num><coll><mfn><an><pl><dat>$",
    "<prn><pos><mfn><aa><pl><acc>$ <num><coll><mfn><an><pl><nom>$",
    "<pr>$ <prn><pos><mfn><an><pl><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<pr>$ <prn><pos><mfn><an><pl><ins>$ <num><coll><mfn><an><pl><ins>$",
    "<prn><pers><p3><m><sg><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<prn><pers><p3><m><sg><dat>$ <num><coll><mfn><an><pl><dat>$",
    "<prn><pers><p3><m><sg><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<pr>$ <prn><pers><p3><m><sg><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<pr>$ <prn><pers><p3><m><sg><gen>$ <num><coll><mfn><an><pl><ins>$",
    "<prn><pers><p3><mfn><pl><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<prn><pers><p3><mfn><pl><gen>$ <num><coll><mfn><an><pl><dat>$",
    "<prn><pers><p3><mfn><pl><gen>$ <num><coll><mfn><an><pl><nom>$",
    "<pr>$ <prn><pers><p3><mfn><pl><gen>$ <num><coll><mfn><aa><pl><acc>$",
    "<pr>$ <prn><pers><p3><mfn><pl><gen>$ <num><coll><mfn><an><pl><ins>$",
    "<prn><pers><p1><mf><sg><dat>$ <num><mfn><pl><nom>$",
    "<prn><pers><p2><mf><sg><dat>$ <num><mfn><pl><nom>$",
    "<prn><pers><p3><m><sg><dat>$ <num><mfn><pl><nom>$",
    "<prn><pers><p1><mf><pl><dat>$ <num><mfn><pl><nom>$",
    "<prn><pers><p2><mf><pl><dat>$ <num><mfn><pl><nom>$",
    "<prn><pers><p3><mfn><pl><dat>$ <num><mfn><pl><nom>$"
]
